# Generated by Django 3.2.5 on 2023-03-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0003_alter_member_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
