# Generated by Django 3.2.5 on 2023-03-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0004_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[(1, 'PAID'), (2, 'Mnimum PAID'), (3, 'Not PAIID')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
