# Generated by Django 3.2.5 on 2023-03-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0007_auto_20230321_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('pending', 'Pending')], max_length=20)),
                ('community_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_Management_App.communitycenter')),
            ],
        ),
    ]
