# Generated by Django 4.1.3 on 2023-03-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0008_centeravailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CenterAvailability',
        ),
    ]
