# Generated by Django 4.1.3 on 2023-03-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0009_delete_centeravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
