# Generated by Django 3.2.5 on 2023-03-31 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend_Management_App', '0010_centeravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_status', models.CharField(choices=[('full', 'Full PAID'), ('minimum', 'Minimum PAID'), ('not_paid', 'Not PAID')], max_length=20)),
                ('booking_status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('booked', 'Booked')], max_length=20)),
                ('play_ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_Management_App.playground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
