# Generated by Django 3.2.5 on 2023-04-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0013_auto_20230402_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bookingground',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='bookingground',
            name='payment_status',
        ),
    ]
